from objetos import * # clases Path y Nodo

NODOS = { 0: Nodo("Estas en tu habitación, lleno de lujos disfrutando tu delicioso almuerzo",
                  [Path(1, "continuar")]),
          1: Nodo("Escuchas gritos provenientes de afuera",
                  [Path(2, "seguir comiendo"), Path(3, "ir a la ventana")]),
          2: Nodo("Comes pero eres interrumpido por un guardia",
                  [Path(4, "Escuchar al guardia")]),
          3: Nodo("Hay un gran alboroto",
                  [Path(4, "Buscar un guardia"), Path(4, "Preguntar que está pasando")]),
          4: Nodo("Te informan que tu padre, el heroe del reino ha sido asesinado",
                  [Path(5, "Te preparas para la guerra"), Path(6, "No aguantas la noticia y corres a encerrarte en tu habitacion")]),
          5: Nodo("Mientras te preparas escuchas a alguien tocar la puerta",
                  [Path(8, "Abres la puerta"), Path(15, "Ignoras el llamado y sigues preparandote para salir")]),
          6: Nodo("Encerrado en tu cuarto escuchas que llaman a tu puerta",
                  [Path(8, "Abres la puerta"), Path(7, "Crees que aún no es el momento de ver a alguien y permaneces encerrado en tu luto")]),
          7: Nodo("Se te acaba la comida y eventualmente mueres de hambre",
                  []),
          8: Nodo("Heraldo te cuenta sobre una organización secreta",
                  [Path(9, "Salir de tu habitación a explorar")]),
          9: Nodo("Te encuentras con una pandilla de bandidos en el pueblo cercano, ¿como te defenderas?",
                  [Path(10, "Ataque de fuego"), Path(10, "Ataque de hielo"), Path(11, "Usar tu espada")]),
          10: Nodo("Este poder no parece funcionar",
                  [Path(9, "Intentar un nuevo ataque")]),
          11: Nodo("Tu espada se rompe y la pandilla te golpea hasta robarte todo y dejarte en el suelo. Un aldeando pasa cerca tuyo",
                  [Path(7, "Los daños no son severos así que buscas descansar donde estás para recuperarte"), Path(12, "Llamas la atención del aldeano")]),
          12: Nodo("Te ayuda pero no cree que tu seas el heroe",
                  [Path(13, "Seguir luchando contra obstaculos")]),
          13: Nodo("La gente se enamora de ti y se unen a luchar contigo",
                  [Path(14, "Ir con tus nuevos amigos a derrocar a la aristocracia "), Path(16, "Entrenar más antes de atacar")]),
          14: Nodo("La gente se enamora de ti y se unen a luchar contigo",
                  [Path(15, "luchar contra la gran defensa aristocrática")]),
          15: Nodo("Eres brutalmente superado en fuerza y derrotado",
                  []),
          16: Nodo("Llegas al palacio con una fuerza imparable y suficiente para conquistarlo. Todos cantan por el heroe.",
                  [Path(17, "Rechazar el canto y ordenas explorar el palacio"), Path(19, "El grupo necesita relajarte, asumir la posición de heroe y unirte a al festejo")]),
          17: Nodo("Satisfecho con tu desición, caminas por los grandes pasillos del palacio",
                  [Path(18, "Seguir explorando en busca de fugitivos")]),
          18: Nodo("Ingresas a una habitación oscura ubicada en el extremo del palacio. Con la poca luz ingresando a través de las cortinas vez algo brillante en el suelo",
                  [Path(20, "Recoger objeto brillante"), Path(21, "Ajustar ojos a la oscuridad")]),
          19: Nodo("Te quedas festejando con todos y te a la fiesta que estaba formandose",
                  [Path(20, "Recoger objeto brillante")]),
          20: Nodo("Sin notarlo, el heroe del otro reino ha caido en la locura y te ataca con una daga envenenada por la espalda",
                  []),
          21: Nodo("Entre las sombras, vez una silueta. Es el heroe del otro reino quien ha caido en la locura y te ataca. Apenas logras defenderte",
                  [Path(22, "luchar"), Path(23, "llamar por ayuda")]),
          22: Nodo("Sientes que no puedes contra él, pero llega el personaje camaleon quien se sacrifica generando una ventana y permitiendote contratacar ganando la batalla",
                  [Path(24, "Asistir a personaje camaleon")]),
          23: Nodo("Mientras llamas por ayuda los ataques del heroe rival te dejan sin aliento. Por suerte, tus gritos fueron escuchados por el personaje camaleon quien se interpone entre tu y el ataque rival recibiendo una herida pero permitiendote contratacar y ganar la batalla",
                  [Path(24, "Asistir a personaje camaleon")]),
          24: Nodo("Con sus ultimas palabras, te dice que fue un honor haberte conocido y que ahora si eres un heroe de verdad. Te despides de él entre lagrimas",
                  [Path(25, "Terminar tu misión")]),
          25: Nodo("Unificas Zarene y Cinait. Ganaste",
                  [])
        }