from objetos import * # clases Path y Nodo

NODOS = { 0: Nodo("Estas en tu habitación, lleno de lujos disfrutando tu delicioso almuerzo. La vida es buena.",
                  [Path(1, "continuar")]),
          1: Nodo("Escuchas gritos provenientes de afuera.",
                  [Path(2, "seguir comiendo"), Path(3, "ir a la ventana")]),
          2: Nodo("Te dispones a seguir comiendo, pero eres interrumpido por la subita entrada de un guardia.",
                  [Path(4, "Escuchar al guardia")]),
          3: Nodo("Hay un gran alboroto, guardias avanzan por el corredor a paso raudo. Las empleadas tiemblan mientras susurran entre ellas, una te mira de reojo y pronto todas se dispersan.",
                  [Path(4, "Buscar un guardia"), Path(4, "Preguntar que está pasando")]),
          4: Nodo("Te informan que tu padre, el heroe del reino ha sido asesinado. De alguna forma encuentras las fuerzas para volver a tu cuarto. Sientes que el mundo da vueltas a tu alrededor, la temperatura desciende subitamente, y la comida que acabas de consumir parece revolverse en tu estomago.",
                  [Path(5, "Te preparas para pelear, quien sea el culpable de esto pagará"), Path(6, "No aguantas la noticia y corres a encerrarte en tu habitacion")]),
          5: Nodo("Mientras te preparas escuchas a alguien tocar la puerta",
                  [Path(8, "Abres la puerta"), Path(15, "Ignoras el llamado y sigues preparandote para salir")]),
          6: Nodo("Encerrado en tu cuarto escuchas que llaman a tu puerta",
                  [Path(8, "Abres la puerta"), Path(7, "Crees que aún no es el momento de ver a alguien y permaneces encerrado en tu luto")]),
          7: Nodo("Te tumbas en tu cama y dejas que el sueño se lleve tu pesadumbre. No sabes cuanto tiempo ha pasado, despiertas con el mismo cansancio con el que empezaste a dormir, no tienes energías para poner un pie afuera. Eventualmente se te acaba la comida y mueres de hambre.",
                  []),
          8: Nodo("En el umbral de la puerta aparece una figura con el semblante sombrío, te cuenta que su nombre es Adeltor. Te cuenta que es amigo de tu padre, que lo estan persiguiendo y que no tiene mucho tiempo, menciona algo sobre una organización secreta, pero no terminas de entender. Adeltor mira con miedo hacia tu ventana, y corre despavorido. Sientes que te falta el aire, que toda tu habitacion es un recordatorio de una gran mentira.",
                  [Path(9, "Tomas un abrigo y sales de tu habitacion")]),
          9: Nodo("Sales de tu casa, y de la ciudad que te vió nacer, caminas sin rumbo fijo. Avanzas atormentado por tus pensamientos, ciego al mundo que te rodea. Unas figuras te cortan el paso y te sacan de tu sopor, una pandilla de bandidos, el pueblo mas cercano es apenas visible, ¿como te defenderás?",
                  [Path(10, "Ataque de fuego"), Path(10, "Ataque de hielo"), Path(11, "Usar tu espada")]),
          10: Nodo("...Este poder no parece funcionar",
                  [Path(9, "Intentar un nuevo ataque")]),
          11: Nodo("Tu espada se rompe y la pandilla te golpea hasta dejarte en el suelo, inconsciente. Un aldeando pasa cerca tuyo, no tienes ninguna de las cosas que traías.",
                  [Path(7, "Los daños no son severos así que buscas descansar donde estás para recuperarte"), Path(12, "Llamas la atención del aldeano")]),
          12: Nodo("Le cuentas que eres el heroe, pero por el estado en el que te ve parece no creerte. Te ayuda a levantarte. \n"
                   "El aldeano te lleva a su casa, durante el camino le diste más detalles de lo que sabes y de lo que pasó, el hombre después de un rato comienza a creer tu historia.\n"
                   "Te cuenta que por estos lugares la vida siempre a sido cruel e injusta, sería bueno que el  héroe les perestara su fuerza...\n"
                   "Luego de contar tu historia al hombre, te das cuenta que no puedes hacer esto solo",
                  [Path(13, "Le cuentas al hombre que necesitas ayuda,")]),
          13: Nodo("El hombre resultó ser el alcade de la pequeña localidad, decide ayudarte... Pronto se corre la voz entre los necesitados. Luego de unos días se ha reunido un buen pelotón de gente. "
                   "La gente harta de los malos tratos que resive por parte de la aristocracia decide confiar en tí, ven una pequeña luz de esperanzas de acabar con su sufrimiente.",
                  [Path(14, "Ir con tus nuevos amigos a derrocar a la aristocracia "), Path(16, "Entrenar más antes de atacar")]),
          14: Nodo("Todos los miembros de tu comitiva luchan con ahínco. Sin embargo, la falta de habilidad es notoria.",
                  [Path(15, "seguir luchando contra la gran defensa aristocrática")]),
          15: Nodo("Eres brutalmente superado en fuerza y derrotado",
                  []),
          16: Nodo("Han pasado unos meses de arduo entrenamiento, haz compartido, sufrido y superados obstaculos junto a tus camaradas "
                   "finalmente se preparan para marchar al palacio. Luego de una larga marcha y escaramuzas llegas al palacio con una fuerza"
                   " imparable y suficiente para conquistarlo. Todos cantan por el heroe.",
                  [Path(17, "Rechazar el canto y lideras la exploración del palacio"), Path(19, "El grupo necesita relajarte, asumir la posición de heroe y unirte a al festejo")]),
          17: Nodo("Satisfecho con tu desición, caminas por los grandes pasillos del palacio",
                  [Path(18, "Seguir explorando en busca de fugitivos")]),
          18: Nodo("Ingresas a una habitación oscura ubicada en el extremo del palacio. Con la poca luz ingresando a través de las cortinas vez algo brillante en el suelo",
                  [Path(20, "Recoger objeto brillante"), Path(21, "Ajustar ojos a la oscuridad")]),
          19: Nodo("Te quedas festejando con todos y te a la fiesta que estaba formandose",
                  [Path(20, "Recoger objeto brillante")]),
          20: Nodo("Sin notarlo, el heroe del otro reino ha caido en la locura y te ataca con una daga envenenada por la espalda",
                  []),
          21: Nodo("Entre las sombras, vez una silueta. Es el heroe del otro reino quien ha caido en la locura y te ataca. Apenas logras defenderte",
                  [Path(22, "luchar"), Path(23, "llamar por ayuda")]),
          22: Nodo("Sientes que no puedes contra él, pero llega el personaje camaleon quien se sacrifica generando una ventana y permitiendote contratacar ganando la batalla",
                  [Path(24, "Asistir a personaje camaleon")]),
          23: Nodo("Mientras llamas por ayuda los ataques del heroe rival te dejan sin aliento. Por suerte, tus gritos fueron escuchados por el personaje camaleon quien se interpone entre tu y el ataque rival recibiendo una herida pero permitiendote contratacar y ganar la batalla",
                  [Path(24, "Asistir a personaje camaleon")]),
          24: Nodo("Con sus ultimas palabras, te dice que fue un honor haberte conocido y que ahora si eres un heroe de verdad. Te despides de él entre lagrimas",
                  [Path(25, "Terminar tu misión")]),
          25: Nodo("Unificas Zarene y Cinait. Ganaste",
                  [])
        }